M48
; DRILL file {KiCad 8.0.1-rc1} date 2024-09-01T13:53:54-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-09-01T13:53:54-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1-rc1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C5.500
%
G90
G05
T1
X24.5Y-26.5
X25.5Y-147.0
X269.0Y-146.0
X269.5Y-26.5
M30
